sudo: required
services: 
  - docker

before_install:
  - docker build -t mrdr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mrdr/react-test npm test -- --coverage

after_success:
  - docker build -t mrdr/multi-client ./client
  - docker build -t mrdr/multi-nginx ./nginx
  - docker build -t mrdr/multi-server ./server
  - docker build -t mrdr/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mrdr/multi-client
  - docker push mrdr/multi-nginx
  - docker push mrdr/multi-server
  - docker push mrdr/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-ap-southeast-1-969450302021 
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
